data:
  fcgr_orig: data/interim/fcgr.pkl
  fcgr_mimic: data/interim/fcgr_mimic.pkl

model:
  n_clusters: 80
  embed_dim: 128

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50
  lambda_entropy: 0.0  # Disable for imbalanced taxa

output:
  model_dir: models/
