data:
  fcgr_orig: data/interim/fcgr.pkl
  fcgr_mimic: data/interim/fcgr_mimic.pkl

model:
  n_clusters: 20
  embed_dim: 128

training:
  batch_size: 512
  learning_rate: 0.00005
  epochs: 150
  lambda_entropy: 0.0  # Disable for imbalanced taxa

output:
  model_dir: models/
