
model:
  input_channels: 1
  output_classes: 1 # Set to 1 for binary classification
dataset:
  k_mer_size: 4 # Example k-mer size to pick from FCGR dict

data:
  fcgr_orig: /content/drive/MyDrive/deepsea_edna_data/fcgr.pkl # Assuming this is your original FCGR data
  fcgr_mimic: /content/drive/MyDrive/deepsea_edna_data/fcgr_mimic.pkl

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 1

output:
  model_dir: models # Directory to save trained models
